name: hpcenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - transformers
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - captum
  - tqdm
  - pyyaml
  - ipython
