#!/bin/bash
#PBS -N preprocess_genqueue
#PBS -l select=1:ncpus=12:mem=50gb
#PBS -l walltime=10:00:00
#PBS -o logs/preprocess_genqueue.out
#PBS -e logs/preprocess_genqueue.err

source ~/miniconda3/etc/profile.d/conda.sh
conda activate hpcenv

# Navigate to the project directory
cd /rds/general/user/ifc24/home/input-error-mechdetect

# Run the preprocessing script
python scripts/preprocess_noheader.py
